
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiderman-rigged-36c40fd392a64aaa935bae39070726bc
Title: Spiderman Rigged
*/
import  {useEffect}  from 'react'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import spiderman_riggedScene from '../assets/3d/spiderman_rigged.glb'
export default function Spiderman(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(spiderman_riggedScene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['hanging'].play();
  }, [])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_6"
                    geometry={nodes.Object_6.geometry}
                    material={materials.CoC_iOS_HER_PPA_SEN_Bmat}
                    skeleton={nodes.Object_6.skeleton}
                  />
                  <group name="unamed" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

